import Swal from 'sweetalert2';

export abstract class notify {
  static close() {
    Swal.close();
  }
  static loading() {
    Swal.fire({
      html: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgba(0, 0, 0, 0) none repeat scroll 0% 0%; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
      <circle cx="50" cy="50" fill="none" stroke="#1b75be" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138">
        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
      </circle>
      <!-- [ldio] generated by https://loading.io/ --></svg>`,
      title: 'Loading...',
      position: 'top',
      allowEnterKey: false,
      allowOutsideClick: false,
      showConfirmButton: false,
    });
  }
  static unauthorized() {
    Swal.fire({
      icon: 'error',
      title: 'Oops...',
      position: 'top',
      text: 'You must be logged in to access this feature',
      buttonsStyling: false,
      confirmButtonText: 'Ok',
      customClass: {
        confirmButton: 'btn btn-primary',
      },
    });
  }
  static wrongCredentials() {
    Swal.fire({
      icon: 'error',
      position: 'top',
      title: 'Oops...',
      text: 'Something went wrong with your credentials!',
      buttonsStyling: false,
      confirmButtonText: 'Retry',
      customClass: {
        confirmButton: 'btn btn-primary',
      },
    });
  }
  static conflictCredentials() {
    Swal.fire({
      icon: 'error',
      position: 'top',
      title: 'Oops...',
      text: 'This email is not available',
      buttonsStyling: false,
      confirmButtonText: 'Retry',
      customClass: {
        confirmButton: 'btn btn-primary',
      },
    });
  }
  static accountCreated() {
    Swal.fire({
      icon: 'success',
      position: 'top',
      text: 'Account created with success!',
      buttonsStyling: false,
      confirmButtonText: 'Ok',
      customClass: {
        confirmButton: 'btn btn-primary',
      },
    });
  }
}
